keboola/indigo-ui

src/indigo/less/indigo.less, src/indigo/less/utilities/spacing.less
Fixes #106 
There are 6 loops, multiplying base (.5rem) with loop number. 
- Loop 1: `.5rem`
- Loop 2: `1rem`
- ...
- Loop 6: `3rem`
Sample, for loop 1:
```css
.m-1 {
margin: 0.5rem;
}
.mt-1 {
margin-top: 0.5rem;
}
.mr-1 {
margin-right: 0.5rem;
}
.mb-1 {
margin-bottom: 0.5rem;
}
.ml-1 {
margin-left: 0.5rem;
}
.mx-1 {
margin-left: 0.5rem;
margin-right: 0.5rem;
}
.my-1 {
margin-top: 0.5rem;
margin-bottom: 0.5rem;
}
.p-1 {
padding: 0.5rem;
}
.pt-1 {
padding-top: 0.5rem;
}
.pr-1 {
padding-right: 0.5rem;
}
.pb-1 {
padding-bottom: 0.5rem;
}
.pl-1 {
padding-left: 0.5rem;
}
.px-1 {
padding-left: 0.5rem;
padding-right: 0.5rem;
}
.py-1 {
padding-top: 0.5rem;
padding-bottom: 0.5rem;
}
```
For now I didn't add classes for reseting.
=> Add mixin for generating spacing classes

.babelrc, package.json, src/indigo/components/AlertBlock.jsx, src/indigo/components/Check.jsx, src/indigo/components/Loader.jsx, src/indigo/components/NewLineToBr.jsx, src/indigo/components/PanelWithDetails.jsx, src/indigo/components/Protected.jsx, src/indigo/components/RefreshIcon.jsx, src/indigo/components/Tree.jsx, src/indigo/components/tree/TreeNode.jsx, yarn.lock
Fixes #82 
Changes:
- all components refactored to ES6
- tune Babel settings (use `env` preset, etc.), move settings to `.babelrc` file
=> Fix react create class warning

src/indigo/less/shame.less
v keboola aplikacich uz classa '.kbc-readmore' nikde nefiguruje
https://github.com/search?q=org%3Akeboola+kbc-readmore&unscoped_q=kbc-readmore
Na tu classu byly naveseny styly pro nadpisy markdownu, ktery uz se neaplikovali.
Nadpisy maji nyni nove velikosti , nevidim moc duvod pro to, aby markdown nadpissy meli jiny velikosti nez zbytek aplikace.
Predchozi stav (s classou .kbc-readmore)
Soucasny stav (.kbc-readmore styly se neaplikuju, muzeme je vyhodit)
=> readmore purge

src/indigo/less/panels.less
fixes https://github.com/keboola/kbc-ui/issues/2122
Myslím, že by mohlo jít o typo. Nebo je důvod proč je tu o 1 pixel více?
=> Detail table panel - row margins

src/indigo/less/main-content.less
fixes: #283
Nav má sice border-right, ale je tam spíše navíc. Navíc není 100% výšky. Content vpravo má border-left přes celou výšku. Takže to zastoupí.
Vyřeší se tím i ten problém se scrollbarem. Protože teď to tam nějak nevychází.
=> Main Content with aside Nav - overflow issue

src/indigo/less/shame.less, src/indigo/less/tables.less
Můžeme použít třeba tu: https://github.com/keboola/kbc-ui/issues/2122
Základní CSS bootstrapu tabulky obsahuje: margin-bottom: 20px. Což nemusí být vždy žádoucí.
=> Table - no margin helper class

src/indigo/less/type.less
Fixes: #183
related https://github.com/keboola/kbc-ui/issues/1354
Jde o to: že 
```css
word-break: break-word;
```
není cross browser podporované. Firefox toto ignoruje (alespoň test v novém Firefoxu). V KBC-UI to je použito ale na dosti místech (viz i issue). Bude lepší asi použít tuto třídu a v případě jako fallback použít "break-all", než aby se třeba ovládací tlačítka posunuli mimo obrazovku.
Jinak `break-word` je použito i na jiných místěch zde v Indigo-ui. Tak by asi stálo za to to projet a případně taky přidat fallbeck nebo nějak jinak vyřešit.
=> Add new helper class - kbc-break-word

src/indigo/less/inline-edit-input.less
Tak ještě jedno kolo CSS.
Flexbox jsem koukal že nemá žádný vliv tam, tak jsem to smazal.
Zajímavý je ten input "vertical-align: middle;" - toto nějak podivně hýbe s celým řádkem, jak tu ve storybook tak s celou drobečkovkou v KBC-UI.
Tlačítku na reset jsem dal menší velikost. Pak má button i ten reset stejnou výšku 26px, což snad trošku pomůže s tím vystředěním, ale na stopro to není. Ještě by bylo možné nechat velikost a upravit line-height. Klidně upravím.
Před:
Po:
=> InlineEditInput - css

src/indigo/less/buttons.less
=> Set text-align and white-space to initial values for inline btn

src/indigo/less/tables.less
Myslím že by bylo lepší udělat ten strom trochu více "kompaktní". I pro přehlednost se mi to líbí více, jako bonus na řádek se vejde více informací.
Třeba job detail:
Před:
Po:
Nakonec jsem to dal od druhé úrovně, aby pro úvodní list byl padding stejný jako když tuto komponentu nepoužiji. Až od druhé úrovně to pak bude kompaktnější.
=> Tree component - padding

src/indigo/less/new-ui/current-user.less, src/indigo/less/new-ui/index.less
Fixes #396 
`current-user` a `projects-list` patří pod `new-ui`. V novém menu tam jsou jiné CSS.
Plus jsem přihodit transparent background aby to pak sedělo s těmi dropdowny v projektu.
=> Fix "auth" related pages

src/indigo/less/new-ui/header.less
Fixes https://github.com/keboola/kbc-ui/issues/3509
- jen přidaná minimální velikost toho dropdown-menu 
- o pidi menší padding inputu
Tady jsou dvě varianty. MinWidth pro dropdown jako to je teď, což je hezčí bez rozkliknutí protože ta šipečka je hezky rovnoměrně za názvem projektu. Nebo minWidtn nahoru k jménu třeba, a pak bude dropdown hezky pod tou ikonkou, ale zase bez rozkliknutí bude divně daleko vpravo. Mě se líbí spíš ta první varianta tak jsem ji nahodil, ale dyštak upravím.
=> Project list styling - min width

src/indigo/less/new-ui/login.less
Pokud mám `:-webkit-autofill` rovnou přilepené u `:focus` a `:valid`, tak firefox ignoruje celý ten blok. Nerozumím proč. Když to takto oddělím tak to funguje ok (valid pokryje asi i ten autofill u Firefoxu to vypadá).
=> Firefox - fix login placeholders

src/indigo/components/JobStatusCircle.js, src/indigo/components/JobStatusCircle.test.js, src/indigo/components/__snapshots__/JobStatusCircle.test.js.snap, src/indigo/less/job-status-circle.less
Přidal jsem styl `canceled`. Ještě tam bylo typo `cancelled` (dvě L) nevím zda schválně historicky nebo to bylo právě typo. Ale opravil jsem to. Po pravdě ani nevím zda máme status `canceled` zda není pouze `terminated`.
Každopándě právě pro `terminated`, `terminatting` a `canceled` tam je nový styl. Černé kolečko. Je to stejné jako má `cancel` label.
=> Terminated job - change status "dot" color

src/indigo/components/InlineEditInput.js, src/indigo/components/Loader.js, src/indigo/components/RefreshIcon.js, src/indigo/components/__snapshots__/ConfirmButtons.test.js.snap, src/indigo/components/__snapshots__/InlineEditInput.test.js.snap, src/indigo/components/__snapshots__/Loader.test.js.snap, src/indigo/components/__snapshots__/RefreshIcon.test.js.snap
Related #405 
Ještě vyhození kbc-icon z Indigo-ui. Pak už asi půjde vyhodit ty CSS.
EDIT: Přidal jsem `fa-fw` k Loaderu. Máme to u většiny ikon tak to bude lepší. Nedochází pak třeba u Refresh komponenty ke skákání té ikonky, protože takto budou mít stejnou šířku.
=> Replace custom kbc-icon icons

src/indigo/components/AlertBlock.js, src/indigo/components/SearchBar.js, src/indigo/components/__snapshots__/AlertBlock.test.js.snap, src/indigo/components/__snapshots__/SearchBar.test.js.snap, src/indigo/less/alerts.less, src/indigo/less/search.less
Fixed #406 
Mažu jen to použití, ty ikonky pak vyhodíme asi naráz..
Do toho `AlertBlock` jsem hodil stejnou ikonku pro oba stavy, myslím že to je v poho. Liší se pak barvou:
Search by měl vypadat skoro stejně. Křížek asi jen trochu "mohutnější".
=> Remove usages of custom react components icons

src/indigo/less/tables.less, src/indigo/less/variables.less
- Koukal jsem že default je zarovnání "top", což jsem pak přepisoval všude v kbc na "middle" tak by to měl být default.
- Upravil jsem také "line-height" (podle figy height 18px a písmo 14px takže ten poměr).
- původně jsem měl "border-color" jako transparent, což není asi ideální, takže jsem to přímo přepsat že prostě tam border nebude. Ale "border-color" jsem definoval, aby to případně použít šlo a border se tam fakt ukázal, navíc tu proměnou využiji i v KBC-UI, tam těch definových borderů bylo více tak se to sjednotí na tomto aspoň pak
=> Update table CSS

src/indigo/less/buttons.less, src/indigo/less/forms.less, src/indigo/less/modals.less, src/indigo/less/tables.less, src/indigo/less/variables.less
V novém UI by paddingy měli být násobkem 4 (zaznělo ve včerejším Zoomu a myslím že i dříve někde).
Tak se přidal variable `@padding-base`. Ostatní paddingu jsou počítány z toho.
Pak jsem koukal že máme nějaké větší tlačítka. Tak jsem to podle Figmy ještě prošel a upravil.
Pro mě zajímavé že font-size je "pouze" 11px. Ale je to vše uppercase a bold tak to asi pak působí jako větší. V návrhu teda bylo `bold` ale dal jsem tam `500`. Klidně poupravím pokud to bude problém. 
Ještě jsem upravil line-height o form-control. Tam podle návrhu to je 1:1 ke font-size. Snad to nebude dělat problému v textarea třeba, ale myslím že by nemuselo.
=> Introduce @padding-base variable and update buttons, forms

src/indigo/less/components/searchbar.less, src/indigo/less/variables.less
Více přiblížené grafice.
Text 11px. Line-height 14px a barva taková šedá. Ta se opakuje na více místech (třeba navigace nahoře) takže jsem z toho udělal variable a použiji to také v KBC-UI. To samé platí pro letter-spacing, také se tento opaakuje na hodně místech. Tak bude fajn to mít jako variable.
=> Update searchbar CSS

src/indigo/less/indigo.less, src/indigo/less/utilities/spacing.less
Fixes #417
Vycházel jsem teda z toho co si připravil.
- varianty 2,1 a 0
- přidaný !important - pokud už tuto třídu použiji tak tu marginy tak přesně chci, tak to dává smysl, pokud by mě to mělo něco přepsat tak to tam vůbec nemusí dávat.. myslím že to tak má i bootstrap 4
- jednotku skipu jsem tam 1em - v kbc-ui máme zatím pouze 0,1,2 tak nemá cenu asi generovat nic navíc, dyštak se upraví
=> Margin & Padding classes

src/indigo/less/components/searchbar.less
Pokud mám jako `additionalAction` nějaký tlačítko s modalem, tak tam může být třeba prázdny span, na takové prvky nechci aplikovat margin.
Related https://github.com/keboola/kbc-ui/pull/3807
=> SearchBar - CSS

src/indigo/less/alerts.less
Fixed https://github.com/keboola/kbc-ui/issues/3845
`@alert-border-radius` vychází s base a ta je 4px, lepší asi explicitně nastavit 8px (podle Figmy).
=> Alerts - update border-radius

src/indigo/less/buttons.less
Fixed https://github.com/keboola/kbc-ui/issues/3862
Fixed https://github.com/keboola/kbc-ui/issues/3861
To jsem si moc nevšiml že jsem tam nechal border, nově teda tlačítka bez border, jediná vyjímka je default tlačítko, kde ale snižuji padding-top/bottom aby seděla celková velikost tlačítka.
Bez borderu se i vyřeší ten "bug" na dashboardu v boxu (výška 81px viz fixes issue).
=> Buttons have no border, except a btn-default

src/indigo/components/PanelWithDetails.js
`labelCollapse` a `labelOpen` může být i react element, array, nebo cokoli co umí React vyrenderovat..
Háže nám to na kbc-ui warning protože tam někdy posílámé objekt (fragment) místo stringu.
=> PanelWithDetails - labels

src/indigo/less/forms.less
Fixed https://keboola.atlassian.net/browse/UI-68
Co jsem se dočetl tak Firefox a asi Edge moc nepodporuje `:after` selektor u `input[checkbox]` a `input[radio]`. Musí se to tam nějak hackovat přes další span, což asi nechcem.
Asi lepší spoléhat na default, každý prohlížeč má teda svůj.
=> Radio, Checkbox input - remove custom styles

src/indigo/less/buttons.less
Toto je ještě něco jiného.
Koukal jsme že SM tlačítka s ikonkou mají velikost cca 32.12px.
Dělal to tam ten margin tak jsem místo toho hodil relative pozici.
Vyhodil jsme jeden duplicitní styl a jednou použil variable.
Plus pro konzistenci jsme nahodil i upravenou velikost marginu pro `icon-addon-left`.
=> Button styles - Do not use margin-bottom

src/indigo/less/components/searchbar.less
Jira issue: https://keboola.atlassian.net/browse/UI-426
takto je to 11.69px na 11.69px, tak asi ok, asi kdyby se hrálo ještě s font-size apod tak se dá přiblížit více ale myslím že i takto to browser bude ve finále renderovat jako 12px
=> Searchbar - bigger reset icon

package.json, src/indigo/components/tree/TreeNode.js
Jira issue: https://keboola.atlassian.net/browse/UI-728
Changes:
- Import Iterable with destructing
- Move immutable to peerDependencies
---
Toto zabezpeci, ze projekty, ktore pouzivaju indigo-ui a zaroven immutablejs, budu mat immutable len 1x.
=> Move immutable to peerDependencies

package.json, src/indigo/components/PanelWithDetails.js, src/indigo/components/__snapshots__/PanelWithDetails.test.js.snap, src/stories/Bootstrap/index.js, src/stories/ModalConfiguration/index.js, src/styles/indigo-storybook.less, yarn.lock
Navazuje na https://github.com/keboola/indigo-ui/pull/452
- update react-bootstrap na 0.33.1
- šlo jen o update `<Panel />` komponent, který změnily docela API, šlo o Panel stories z bootstrapu + naší komponentu `<PanelWidthDetails />`
Pokud by to bylo vše ok asi bych to vydal jako verzi 13 pro jistotu. Když bude potřeba upravit i KBC-UI před použitím.
=> Update react bootstrap

.travis.yml, README.md
Jira issue: https://keboola.atlassian.net/browse/UI-1613
Changes:
- Use Node 14 for local development and build
---
Opat len Node na 14ku.
=> Use Node 14 for local development and build

package.json, yarn.lock
Jira issue: https://keboola.atlassian.net/browse/UI-1745
Changes:
- update react
- update "react-input-autosize", tam je jen podpora pro react 17 + nepoužívá to unsafe lifecycle
- update fortawesome knihovny na to co máme v kbc-ui
- update peer dependencies aby to sedělo s tím co máme teď v kbc-ui
- minor update react-scripts, jen že tam bylo 4.0.1 takže ranná major verze tak že třeba oprava nějakých bugů nebo tak
Ono to ničemu nevadilo že to nebylo aktualizované protože se používá ten react ke pak používáme indigo, ale fajn aby to sedělo tu při vývoji s tím co bude pak tam kde se to použije.
=> Indigo - update react & basis dependencies

package.json, src/indigo/components/InlineEditInput.js, src/indigo/components/__snapshots__/InlineEditInput.test.js.snap, src/stories/InlineEditInput/examples/InlineEditInput.js
Navazuje na https://github.com/keboola/indigo-ui/pull/462
Jira issue: https://keboola.atlassian.net/browse/UI-1746
Changes:
- "esc" ukončí editaci (v kbc-ui už to máme pro inline editaci code name v nových transformací a u inline edit area která je třeba u description, toto je poslední místo kde se to doplní ať je to jednotné)
- placeholder se doplní i do inputu když edituji (je na userovi ať tu hlášku připadně upraví pro edit, má nad tím plnou kontrolu)
- trošku jsme zjednodušil focus, tam to není potřeba ukládat do komponenty
- přidaná props na skrytí edit ikonky
Jinak tu už používám `e.key` teda místo `keyCode` co máme v kbc-ui. Ten `keyCode` je deprecated tak aspoň tu už takto líp. Koukám zde a jsou tam dvě možnosti https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key#exa …
=> Indigo - inline edit input - placeholder

src/indigo/components/InlineEditInput.js, src/indigo/components/__snapshots__/InlineEditInput.test.js.snap
Changes:
- Add default `true` value to `isValid` prop
- Remove events and prevent default in `onEditStart` and `onEditCancel` handlers
---
ref.: https://github.com/keboola/kbc-ui/pull/6364#discussion_r713616061
=> Tune inline edit text input

src/indigo/components/ConfirmButtons.js
Jira issue: https://keboola.atlassian.net/browse/UI-3034
Changes:
- přidaná možnost nastavit submit buttonu custom třídy, využití v UI je právě teď pro ty externí třídy, abych je mohl přidat k submitu
Už máme props `saveLabel`, `saveStyle` tak ve stejném stylu přidáno `saveButtonClass`. Nebo nevím zda lepší název třeba jen `saveClass`.
=> Allow add custom class to submit button in ConfirmButtons component
