.travis.yml

Setup npm deploy

---

package.json
yarn.lock

Add react-bootstrap dependency

---

package.json

Add react and react-dom peer dependencies

---

.storybook/addons.js
.storybook/config.js
package.json
yarn.lock

Add knobs addon and its configuration

---

.travis.yml

- Updated script section to be joined with `&&` (stop on error)
- Add missing `repo` and `branch` setting to 3rd deploy script

Tune travis script

---

.travis.yml
package.json
src/indigo/components/Check.jsx
src/indigo/components/Loader.jsx
src/indigo/components/NewLineToBr.jsx
src/indigo/components/Protected.jsx
src/indigo/components/RefreshIcon.jsx
src/indigo/components/Tree.jsx
src/indigo/components/index.js
src/indigo/components/tree/TreeNode.jsx

Migrate kbc-react-components

---

package.json
yarn.lock

Fixes #74 
- Lower react-bootstrap dependency, move to `peer` section

Tune peer dependencies

---

.storybook/config.js
src/stories/Check/index.js
src/stories/Loader/index.js
src/stories/NewLinToBr/index.js
src/stories/Protected/index.js
src/stories/RefreshIcon/index.js
src/stories/Tree/index.js

Fixes #77 
Init stories for former kbc-react-components.
Some of them will be improved with planned warning fixing, etc.

Add stories for former kbc-react-components

---

.dev/nginx/nginx.conf
Gruntfile.js
README.md
docker-compose.yml
package.json
public/kbc-dev-manifest.json

Related to #96 
Changes:
- revert `https` settings
- add simple nginx proxy

Add simple proxy; Revert https settings

---

src/indigo/less/components/tabs.less
src/indigo/less/indigo.less

Init styles for tabs

---

src/indigo/less/navs.less

Remove old tab-pane styles

---

src/indigo/less/components.less

fix: align to top

---

src/indigo/less/components/tabs.less
src/indigo/less/indigo.less

Replaces tabs temp solution

---

.travis.yml
package.json
src/indigo/components/Check.test.js
src/indigo/components/Loader.test.js
src/indigo/components/NewLineToBr.test.js
src/indigo/components/Protected.test.js
src/indigo/components/RefreshIcon.test.js
src/indigo/components/Tree.test.js
src/indigo/components/__snapshots__/Check.test.js.snap
src/indigo/components/__snapshots__/Loader.test.js.snap
src/indigo/components/__snapshots__/NewLineToBr.test.js.snap
src/indigo/components/__snapshots__/Protected.test.js.snap
src/indigo/components/__snapshots__/RefreshIcon.test.js.snap
src/indigo/components/__snapshots__/Tree.test.js.snap
src/tests.js
yarn.lock

Fixes #80 
Changes:
- init snapshot tests for components

Init snapshot tests

---

src/indigo/components/NewLineToBr.jsx
src/indigo/components/NewLineToBr.test.js
src/indigo/components/Protected.jsx
src/indigo/components/RefreshIcon.jsx
src/indigo/components/__snapshots__/NewLineToBr.test.js.snap
src/indigo/components/__snapshots__/RefreshIcon.test.js.snap
src/indigo/components/tree/TreeNode.jsx

Fixes #79 
Changes:
- fix few warnings
- small refactoring of some components

Fix former kbc react components

---

src/indigo/less/outer-pages.less

Helps fix: https://github.com/keboola/kbc-ui/issues/1443
This is a requirement for: https://github.com/keboola/connection/pull/1184

Style for outer pages logo link

---

src/indigo/less/components/tabs.less
src/indigo/less/indigo.less

This reverts commit 0cb3fe76b5f496d758a8bd336f00dfb90855b81a.
Fixes #111

Replaces tabs temp solution (round 2)

---

.storybook/config.js
src/indigo/components/ExternalLink.jsx
src/indigo/components/ExternalLink.test.js
src/indigo/components/__snapshots__/ExternalLink.test.js.snap
src/stories/ExternalLink/index.js

Fixes #113 
- ExternalLink component, its story and snapshots

Add external link component

---

.storybook/config.js
src/indigo/less/panels.less
src/stories/PanelShowDetails/index.js

Related to https://github.com/keboola/kbc-ui/issues/1485

adds styles and showcase for PanelShowDetails

---

src/indigo/less/shame.less

neni to nejcistejsi reseni, ale prozatim myslim dostatecny. Nechce se mi kvuli tomu upraovovat vsechny .kbc-buttons v soucasny okamzik. Proto to davam do shame.css a komentuju

adds additional styles for kbc-buttons in ex-fb

---

.storybook/manager-head.html
.storybook/preview-head.html
src/indigo/less/variables.less
src/styles/indigo-storybook.less

Improve storybook layout

---

.storybook/config.js
src/stories/Bootstrap/index.js
src/stories/Tabs/index.js

adds tabs story

---

src/stories/Bootstrap/index.js
src/stories/PanelWithDetails/index.js

Vsiml jsem si, ze tu dochazi k nejakymu zmateni. https://keboola.slack.com/archives/C0LM9SK6K/p1523891363000557 .
Asi pravem, kdyz ta vec nema dostatecny popis. Takze uvadim na pravou miru

adds description / explanation to components

---

src/stories/Bootstrap/index.js

Doplnuju priklad ktery mi tu chybel, vzdycky ho lovim

adds example of centered image

---

src/stories/Bootstrap/index.js

changes component display to 'inline'

---

src/indigo/components/AlertBlock.jsx
src/indigo/components/AlertBlock.test.js

Fixes #151 
Changes:
- rename prop to fix conflict

Rename AlertBlock prop (to fix conflict with style prop)

---

src/indigo/components/PanelWithDetails.jsx
src/indigo/components/PanelWithDetails.test.js
src/indigo/components/__snapshots__/PanelWithDetails.test.js.snap
src/indigo/less/panels.less
src/stories/PanelWithDetails/index.js

Jan detail bottom controls

---

src/indigo/less/alerts.less

improves alert block styles for passed content

---

package.json
src/indigo/components/AlertBlock.jsx
src/indigo/components/Check.jsx
src/indigo/components/ExternalLink.jsx
src/indigo/components/Loader.jsx
src/indigo/components/NewLineToBr.jsx
src/indigo/components/PanelWithDetails.jsx
src/indigo/components/Protected.jsx
src/indigo/components/RefreshIcon.jsx
src/indigo/components/Tree.jsx
src/indigo/components/tree/TreeNode.jsx
yarn.lock

Use PropTypes from prop-types package

---

src/indigo/components/Protected.jsx

Related to https://github.com/keboola/kbc-ui/issues/1713
Bug introduced during refactor to React.Component

Fix revealing of content in Protected component

---

src/indigo/less/forms.less
src/indigo/less/type.less

Fixes https://github.com/keboola/kbc-ui/issues/988

unifies text form inputs to same height

---

src/indigo/less/buttons.less
src/indigo/less/search.less
src/indigo/less/sidebar.less
src/indigo/less/type.less

fixes #215
fixes #214
fixes #213

styles according to same height inputs

---

src/indigo/less/outer-pages.less
src/indigo/less/shame.less
src/indigo/less/sidebar.less

Remove indigo-temp classes

---

src/indigo/less/kbc-user.less
src/indigo/less/outer-pages.less

Splash text fixes

---

src/indigo/less/labels.less

fixes https://github.com/keboola/kbc-ui/issues/1838
fixes https://github.com/keboola/kbc-ui/issues/1917

[r4r] align phase label 

---

src/indigo/less/shame.less
src/indigo/less/sidebar.less

Fixes #235 
Fixes keboola/connection#1485

fixes styles for select-project

---

src/indigo/less/kbc-user.less
src/indigo/less/outer-pages.less

[r4r] Dropdown element overflow

---

src/indigo/less/buttons.less

Revertuju to kvuli tomuto tasku https://github.com/keboola/indigo-ui/issues/182
Abych to mohl udelat dle navrhu, potrebuju vratit zpet border buttonum, jinak spravne nefunguje btn-group 
Zvalidoval jsem to s produkci, dokonce mi pripada ze to vypada lip.

Button border style

---

src/indigo/less/kbc-user.less

maly fix konfliktu, jak jsem psal tady
https://github.com/keboola/indigo-ui/pull/233#issuecomment-414267807

fixes padding caused by invisible border

---

.storybook/config.js
src/indigo/less/buttons.less
src/stories/RegionSelector/index.js

[r4r] Region selector

---

src/indigo/components/SearchBar.jsx
src/stories/SearchBar/index.js

Add support for inputRef; Add story showing ref usage

---

src/indigo/less/shame.less

Related to: https://github.com/keboola/kbc-ui/issues/2032

padding class name

---

src/indigo/components/SearchBar.jsx
src/indigo/components/__snapshots__/SearchBar.test.js.snap
src/indigo/less/search.less

Fixes #260 
Fixuje to problem s tym, ze additional actions boli vnutri formulara. Tym padom bolo mozne pridat tam nieco, co by bolo nevalidne - napr. dalsi formular. Takisto by sa mohlo stat, ze niekto prida submit button a bude sa to spravat divne (ako napr. tu https://github.com/keboola/kbc-ui/commit/5fd6302424850ab14340e2e24090723a9e18b9d7)

Move additional actions outside of a form

---

src/indigo/less/sidebar.less

fixes https://github.com/keboola/indigo-ui/issues/269

Focus styles

---

src/indigo/less/panels.less

fixes #276 
Sel jsem cestou specifictejsiho selectoru.
Dle ostatnich domo prikladu v Indigu to nic nerozbilo

Collapse overflow

---

.storybook/config.js
src/indigo/less/modals.less
src/stories/ModalConfiguration/index.js

zbyle styly a demo (ne komponenta) pro https://github.com/keboola/kbc-ui/pull/2072
followup https://github.com/keboola/indigo-ui/pull/275

Config form demo

---

src/indigo/less/head.less
src/indigo/less/indigo.less
src/indigo/less/sidebar.less
src/indigo/less/variables.less

related: https://github.com/keboola/kbc-ui/pull/2099
wait: https://github.com/keboola/kbc-ui/pull/2143
wait: https://github.com/keboola/kbc-ui/pull/1996#issuecomment-420314876
Extrahování CSS z KBC-UI pro lepší mobilní zobrazení.

Mobile sidebar css updates

---

src/indigo/less/head.less
src/indigo/less/indigo.less
src/indigo/less/sidebar.less

Revert "Mobile sidebar css updates"

---

src/indigo/less/shame.less

Jeste jsem nasel jeden nepouzivany styl

Unused style

---

src/indigo/less/components.less
src/indigo/less/shame.less

Vyzhozeni uppercase
Pridani stylu pro vyber tasku v orchestracich

Styles for descriptions

---

src/indigo/components/SearchBar.js
src/indigo/less/search.less
src/stories/SearchBar/index.js

Clearable Searchbar

---

src/indigo/components/SearchBar.js
src/stories/SearchBar/index.js

Fixes: https://github.com/keboola/kbc-ui/issues/2228

Call onSubmit "on clear"; Add story with example

---

src/indigo/components/SearchBar.js
src/indigo/components/SearchBar.test.js
src/indigo/components/__snapshots__/SearchBar.test.js.snap
src/stories/SearchBar/examples/AutoSubmitOnClear.js
src/stories/SearchBar/examples/BasicUsage.js
src/stories/SearchBar/examples/Events.js
src/stories/SearchBar/examples/WithButtons.js
src/stories/SearchBar/examples/WithExternalButtons.js
src/stories/SearchBar/examples/WithRef.js
src/stories/SearchBar/index.js

Searchbar value from prop

---

src/indigo/components/SearchBar.js

Related to: https://github.com/keboola/kbc-ui/pull/2219

Wait 50ms before calling onSubmit when clearing value

---

package.json
yarn.lock

Nenašel jsem v ./src ani jinde využití.

Remove unused library - fixed-data-table

---

src/indigo/less/modals.less
src/indigo/less/shame.less

fixes https://github.com/keboola/kbc-ui/issues/2405

Inline btn float style

---

src/indigo/less/modals.less
src/indigo/less/shame.less

Revert "Inline btn float style"

---

src/indigo/less/modals.less
src/indigo/less/shame.less

Proper fix for ConfirmButtons

---

.storybook/config.js
package.json
src/indigo/components/Finished.js
src/indigo/components/Finished.test.js
src/indigo/components/__snapshots__/Finished.test.js.snap
src/indigo/components/index.js
src/indigo/less/finished.less
src/indigo/less/indigo.less
src/stories/Finished/index.js
yarn.lock

Jeste to potrebuju projit a vyscreenovat

Finished component migration

---

src/indigo/components/InlineEditInput.js
src/indigo/components/__snapshots__/InlineEditInput.test.js.snap
src/indigo/less/inline-edit-input.less

Tak bych ještě doplnil nějaké CSS. V KBC-UI jsou nějaké parent styly jiné (asi font-size) a pak se to rozbije trošku. Tak bych tu doplnil přímo nějaký. Plus bych save text udělal obecně o trošku větší.
Bez úprav to v KBC vypadá takto:
Když jsem aplikoval tyto další CSS:

Inline Edit Input - CSS update

---

src/stories/Finished/index.js

https://github.com/keboola/indigo-ui/pull/315#pullrequestreview-180034588

Finished knob to demo

---

src/indigo/less/icons.less
src/indigo/less/shame.less

Dalsi mesni cisteni
- presunul jsem iconovy classy do prislusnyho stylesheetu
- zbavil jsem se jednoho selectoru, ktery tvoril zavislost na okolnich selectorech na `.kbc-icon-fw` (obdoba .fa-fw) V KBC se to vyskytovalo jen jednou

Icon purge

---

src/indigo/components/Finished.test.js
src/indigo/components/__snapshots__/Finished.test.js.snap

fixes https://github.com/keboola/indigo-ui/issues/345

fixes Finished snapshot

---

src/indigo/components/JobStatusCircle.js
src/indigo/components/JobStatusCircle.test.js
src/indigo/components/__snapshots__/JobStatusCircle.test.js.snap
src/indigo/less/job-status-circle.less

Related to #316
Changes:
- status prop as not required
- simplify class name

JobStatusCircle fixes

---

src/indigo/less/search.less

Remove font-size settings for searchbar input

---

src/indigo/components/ExternalLink.js
src/indigo/components/ExternalLink.test.js
src/indigo/components/__snapshots__/ExternalLink.test.js.snap
src/stories/ExternalLink/index.js

Fixes: https://github.com/keboola/kbc-ui/issues/3139
Allow "any prop" on ExternalLink component

External link props

---

src/indigo/less/indigo.less
src/indigo/less/kbc-admin-project-overview.less

Related https://github.com/keboola/kbc-ui/pull/3140
Migrace CSS z KBC-UI sem.

Project Graph - CSS

---

src/indigo/less/kbc-admin-project-overview.less

Related https://github.com/keboola/kbc-ui/pull/3196
CSS pro search input
CSS pro větší texty

Project graph - CSS v2

---

.storybook/preview-head.html

Fixes: #196
Changes:
- load Roboto font

Load Roboto in storybook

---

src/indigo/less/buttons.less
src/indigo/less/forms.less
src/indigo/less/legacy.less
src/indigo/less/limits.less
src/indigo/less/navs.less
src/indigo/less/outer-pages.less
src/indigo/less/shame.less
src/indigo/less/sidebar.less
src/indigo/less/single-pages.less
src/indigo/less/type.less
src/indigo/less/variables.less

Fixes #370
Nakonec teda: 
300 -> 400 (nejbližší co načítáme)
600 -> 500
Takto si to myslel? Tam asi bude i tak hodně lazení až to pak uvidíme někde v celku. Myslím že obecně by se mohl nastavit nějaký větší letter-spacing aby to nebylo tak na sobě.

Replace Whitney font by Roboto

---

src/indigo/less/forms.less

https://github.com/keboola/indigo-ui/issues/351

Static form element alignment

---

src/indigo/less/new-ui/login.less

Related #3263
Vyřeší to tento problém https://github.com/keboola/kbc-ui/issues/3263#issuecomment-487353855

New UI - update login page CSS

---

src/indigo/less/new-ui/login.less

Related https://github.com/keboola/kbc-ui/pull/3270

New UI - Login page - add back-link css

---

src/indigo/less/panels.less

PanelWithDetails + Markdown - link in last row was not clickable

---

src/indigo/less/navs.less

Related https://github.com/keboola/kbc-ui/pull/3306
Přidané stejný styly pro button jako máme pro odkaz v navigaci.

Nav - add disabled styles also for button

---

src/indigo/less/new-ui/current-user.less
src/indigo/less/new-ui/index.less
src/indigo/less/new-ui/login.less
src/indigo/less/new-ui/projects-list.less

Related https://github.com/keboola/kbc-ui/pull/3286
Přesunuto z KBC-UI + pár pidi úprav.

New UI - Projects List - CSS

---

src/indigo/less/new-ui/index.less
src/indigo/less/new-ui/login.less

Fixed https://github.com/keboola/kbc-ui/issues/3384 - přidaný pointer
Fixed https://github.com/keboola/kbc-ui/issues/3382  - přidaný color
Related https://github.com/keboola/kbc-ui/issues/3383 - jen přidaný i margin nahoru, nemělo by to ovlivnit moc grafiku protože se to nesčítá, jen když tam bude alert treba bude trochu odsazený

New UI - CSS update

---

src/indigo/less/new-ui/login.less
src/indigo/less/new-ui/projects-list.less

Rozdělil jsem ten `margin-top: 100px` na top + bottom. Ještě jsem jeden margin zvětšil aby to bylo stejné jak pro login tak pro projects-list.

New UI - update css

---

src/indigo/less/new-ui/login.less

Related https://github.com/keboola/kbc-ui/issues/3400
Nedávám fixed protože to určo neřeší vše. 
Asi zbytek případně nějak vyřešit v KBC-UI. Třeba nějak zobrazit jen mail po znak @ pro dlouhé emaily nebo něco takového. 
Pro overview jsem oddělal fixed posizi pro menší obrazovky. Aby to respektovalo padding lépe. Fixed tam je aby se hýbala pouze ta levá strana když tam mám scrollbar, ale zase na menší obrazovce ta levá strana nevypadá ok, tak bude asi lepší aby nebyla static a byl tam ten padding zachován.

New UI - smaller main padding for smaller screens

---

src/indigo/less/new-ui/helpers.less
src/indigo/less/new-ui/projects-list.less

Related https://github.com/keboola/kbc-ui/issues/3401
Není to teda stopro podle toho screenu. Ta šedá se mi nečetla úplně dobře tak jsem tam nechal default tu "černou". Ale klidně upravím ještě na nějakou lepší.

New UI - Projects list - no projects css

---

src/indigo/less/new-ui/current-user.less

Fixes https://github.com/keboola/kbc-ui/issues/3400
Přidané teda `text-overflow: ellipsis`.

New UI - Current User - text overflow

---

src/indigo/less/new-ui/current-user.less

Related https://github.com/keboola/connection/pull/2028
Ještě bych pak udělal malou úpravu:
Teď:
Nově:

New UI - ProjectsSelect - CurrentUser - Update dropdown menu CSS

---

src/indigo/less/kbc-admin-project-overview.less

Related https://github.com/keboola/kbc-ui/pull/3427

Project Overview - Header css

---

src/indigo/less/new-ui/header.less
src/indigo/less/new-ui/main.less

Super drobnost. Jen vycentrování dropdown ikonky na střed. Nemusí to tam jít asi ani hned.

New UI - dropdown - picker icon

---

src/indigo/less/new-ui/header.less

Pokud mám třídu `max`. Tak zobrazím větší "kolečko". Nechtěl jsem již zmenšovat text ale také by to bylo řešení.
I základní velikost jsem zvedl z 15px na 16px. Aby se tam lépe vešly i dvouciferné hodnoty.

Notifications badge count

---

src/indigo/less/shame.less

v kbc se nikde nevyskytuje https://github.com/keboola/kbc-ui/search?q=kbc-table-selector-edit&unscoped_q=kbc-table-selector-edit

Unused table-selector style

---

src/indigo/less/indigo.less
src/indigo/less/not-available.less

fixes https://github.com/keboola/indigo-ui/issues/249

NotAvailable component

---

.storybook/config.js
src/indigo/components/ConfirmButtons.js
src/indigo/components/ConfirmButtons.test.js
src/indigo/components/__snapshots__/ConfirmButtons.test.js.snap
src/indigo/components/index.js
src/indigo/less/buttons.less
src/indigo/less/modals.less
src/indigo/less/shame.less
src/stories/ConfirmButtons/index.js

fixes https://github.com/keboola/indigo-ui/issues/296

Confirm Buttons

---

src/indigo/less/new-ui/project-select-results.less

Project list - project names capitalization

---

src/indigo/components/AlertBlock.test.js
src/indigo/components/Check.test.js
src/indigo/components/ConfirmButtons.test.js
src/indigo/components/Duration.test.js
src/indigo/components/DurationDynamic.test.js
src/indigo/components/ExternalLink.test.js
src/indigo/components/Finished.test.js
src/indigo/components/InlineEditInput.test.js
src/indigo/components/JobStatusCircle.test.js
src/indigo/components/Loader.test.js
src/indigo/components/NewLineToBr.test.js
src/indigo/components/PanelWithDetails.test.js
src/indigo/components/Protected.test.js
src/indigo/components/RefreshIcon.test.js
src/indigo/components/SearchBar.test.js
src/indigo/components/Tree.test.js
src/tests.js

* rename `snapshot` to `matchesSnapshot` so it well describes what this function does.
* ExternalLink - remove random props (bad practise), add title, force string className
* fix ConfirmButtons.test code style

Minor fixes

---

src/indigo/less/components/inline-edit-input.less

Tam ten button byl moc veliký.
Asi obecně budu muset mrknout ještě na `.btn`. Protože to ovlivňuje více věcí než bych rád.
Jinak ve Figmě jsem nenašel otevřenou editaci (tuto komponentu) takže grafiku jsem dělal jen podle vzhledu co se mi zdálo ok.

Update Inline edit input CSS

---

src/indigo/components/SearchBar.js
src/indigo/components/SearchBar.test.js
src/indigo/components/__snapshots__/SearchBar.test.js.snap

Fixes https://github.com/keboola/kbc-ui/issues/3744

SearchBar - autoFocus is by default set to false

---

src/indigo/less/components/searchbar.less
src/indigo/less/variables.less

Fixes https://github.com/keboola/kbc-ui/issues/3769

SearchBar - Update placeholder styles

---

src/indigo/components/Tree.js
src/indigo/components/__snapshots__/Tree.test.js.snap
src/indigo/less/components/tree.less
src/indigo/less/indigo.less

- akorát zalamování (všiml jsem si toho v modalu v job detail kde to teklo ven, "kb-tree" třída nebyla vůbec stylována)
- přidaný menší padding (to je teď přímo v kbc-ui, pak můžeme vyhodit)

Init Tree CSS

---

src/indigo/less/forms.less
src/indigo/less/variables.less

Super drobnost ale bude se to pak hodit. Už to máme v KBC asi na 5 místech.
A když máme tu `wider` tu tak asi i tata variable by měla být tu.

Add letter-spacing-narrower variable, update control-label font-weight

---

src/indigo/components/PanelWithDetails.js
src/indigo/components/__snapshots__/PanelWithDetails.test.js.snap

Panel with details - add arrows

---

src/indigo/less/buttons.less

Ještě úprava CSS úplně bez toho mixinu ať mám stopro kontrolu.
Zvedá se tam jeden padding - takže button bude mít default 40px místo 38px. V kbc-ui jsou pak nějaké menší i tak to budu muset napevno upravit tam.

Buttons - CSS

---

src/indigo/less/buttons.less
src/stories/Bootstrap/index.js

- ještě úprava horizontálního paddingu (upravovali jsme vertikální) tak aby seděla velikost pokud třeba měním style jen (stejný tlačítko jen měním style, nechci aby se měnila velikost)
- upravil jsem CSS pro default button, nevím teda zda by měl být transparent.. ale myslím že by to mohl být default, a případně upravím když budu potřebovat jiný, ono to většinou i tak bude na bílém pozadí.. ale nemusí být vždy a třeba u toho přepínače Json Editoru tam je průhledné pozadí.
- pro `btn-link-inline` jsem hodně věcí upravil z `initial` na `inherit` aby to vždy co nejlépe sedělo do daného contextu, když to bude v textu kde je velikost 14px tak ať to je taky 14px apod

Default button styles

---

package.json
src/indigo/components/InlineEditInput.js
src/indigo/components/__snapshots__/InlineEditInput.test.js.snap
src/indigo/less/components/inline-edit-input.less
src/stories/InlineEditInput/index.js
yarn.lock

Fixes https://github.com/keboola/kbc-ui/issues/4019
- nová grafika podle Figmy
- velikost atd se snažím brát od předka aby to vždy co nejlépe sedlo do kontextu (nadpis, normal inline text v textu apod)
Btw:
- indigo mi moc nereaguje na změny, než jsme toto udělla tak jsem asi 30krát vypnut server a zase nastartoval
- jak se dělalo kupa změn tak mi nejde `yarn link` abych to testnul rovnou v kbc-ui, je to teda trošku na blink, ale to by se pak vyladilo, jak vzhled tak snad tato funkce

Inline edit input

---

src/indigo/components/InlineEditInput.js
src/indigo/components/__snapshots__/InlineEditInput.test.js.snap
src/indigo/less/components/inline-edit-input.less

- upravil/opravil jsem CSS tam mezi `inline-edit-input` a `form-control` je div protože tam je ta knihovna na tu dynamickou velikost, to mi ušlo
- přidal jsme třídu přímo k inputu kdyby bylo potřeba v kbc třeba něco negovat nebo přímo upravit je tu

Inline Edit Input update

---

src/indigo/less/components/searchbar.less

Nově máme velikost 16px a placeholder není uppercased.
Možné bude potřeba upravit nějaké searchbary pak v kbc-ui (projekty, buckets ve storage možná - se pak uvidí). Ale toto bude nový základ.

Update searchbar styles

---

src/indigo/less/buttons.less
src/stories/Bootstrap/index.js

Upravené CSS tlačítek.
- menší padding aby se vešla větší ikonka
- upravené stories aby tam byly také tlačítka s ikonkama
- rovnou jsem upravit CSS pro font-awesome aby v tlačítku nebyly tak malé.. jdu přes `min-width` a `min-height` abych zajistil jen minimální velikost.. pokud mám někde větší ikonku v tlačítku (třeba navbar-link) tak abych jí tímto nezmenšil.

Buttons styles

---

src/indigo/less/buttons.less
src/stories/Bootstrap/index.js

Related to #446 
Changes:
- Add more stories
- Fix `default` buttons
- Remove button height (computed from line-height and padding)
---
nahodil som to do UI a este som si vsimol nejake nezrovnalosti.

Remove button height, tune styles a bit; Add more stories

---

src/indigo/less/variables.less

Upraveno z 600px na 636px co je velikost ve Figmě.

Change basis modal width

---

src/indigo/less/modals.less
src/indigo/less/variables.less
src/stories/Bootstrap/index.js

Changes:
- New color (gray-medium)
- Fix modal header border
- Tune style for hr line in modal body
- Close btn position and color
---
Poladnych par drobnosti

Tune modal styles

---

.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
Dockerfile
README.md

Jira issue: https://keboola.atlassian.net/browse/UI-479
Changes:
- Update node to v12
- Tune readme a bit
- Add issue template
---
Nech uz je to rovnake na 3 hlavnych repositories.

Node 12 + readme tuning

---

src/indigo/less/buttons.less

Jira issue: https://keboola.atlassian.net/browse/UI-1045
Changes:
- marigny upravený na 10px

Btn-link - smaller margin between icon and label

---

src/indigo/less/badges.less
src/indigo/less/components/searchbar.less
src/indigo/less/indigo.less
src/indigo/less/label.less
src/indigo/less/modals.less
src/indigo/less/popover.less
src/indigo/less/tooltip.less
src/indigo/less/variables.less
src/indigo/less/well.less
src/stories/Bootstrap/index.js

Jira issue: https://keboola.atlassian.net/browse/UI-1093
Changes:
- přesunul jsem zde základní CSS bootstrap komponent z KBC-UI, kde šlo využít nějaké bootstrap variables tak jsem upravit, jinak jsem doplnil přímo CSS
- upravený footer modalu, tam jsem koukal na Figmu a spodní padding je různé od 30px do 34px, nechal jsem teda 30px 
Na základní bootstrap komponenty tam jsou stories takže jdou vidět úpravy tam.
Jak se tam použije tato nové verze tak tam ty základní CSS vyhodím.

Indigo UI - move some basis CSS to Indigo from KBC-UI

---

.storybook/preview-head.html
src/indigo/less/badges.less
src/indigo/less/buttons.less
src/indigo/less/components/searchbar.less
src/indigo/less/indigo.less
src/indigo/less/label.less
src/indigo/less/modals.less
src/indigo/less/variables.less

Jira issue: https://keboola.atlassian.net/browse/UI-1968
Changes:
- Remove Roboto loading
- Add native font stack from Bootstrap 5
- Tune buttons
---
Zatial takto, uvidim, ked to napojime do UI. Spravim novu major verziu a release bude zatial alfa.

Native font stack init

---

package.json
src/indigo/components/ConfirmButtons.js
src/stories/ConfirmButtons/index.js

Jira issue: https://keboola.atlassian.net/browse/UI-1619 (part)
Changes:
- přidaná prop pro "block" button
Ten má i ikonku pokud to není danger styl, tam tuším ikonky moc nemáme.

Confirmbutton has new 'block' prop

---

Gruntfile.js

Changes:
- oprava toho pravidla aby to bralo i soubory mimo příom tu less složku ale i níže

Grunt - watch fix

---

.travis.yml
README.md
package.json

Jira issue: https://keboola.atlassian.net/browse/UI-2910
Changes:
- update na node v16
Zase nebylo potřeba nic měnit. Ono asi tam není nic extra jinak no. Obě jsou nové verze docela.

Update node to v16

---

package.json

Changes:
- povolení node 14 kvůli vercelu

Allow also node 14

---

package.json

Changes:
- Allow node >=16
---

Allow node >=16

---

.github/workflows/tag.yml
src/indigo/components/StatusCircle.js
src/indigo/components/__snapshots__/StatusCircle.test.js.snap

Jira issue: https://keboola.atlassian.net/browse/UI-3166
Changes:
- Simplify `StatusCircle` component
- Update icons
---
Nově má error červený vykřičník, cancelled/terminated šedý vykřičník

update icons + simplify component

---

src/indigo/components/StatusCircle.js
src/stories/StatusCircle/index.js

Jira issue: https://keboola.atlassian.net/browse/UI-3352 (part)
Changes:
- warning by neměl být "danger" ale žlutý, stejně jako to máme v jobs

warning should have warning style
